[tool.briefcase]
project_name = "OCI Session Manager"
description = "A tool for managing OCI Bastion sessions."
bundle = "com.phluxapps"
version = "1.0.0"
url = "https://github.com/jcphlux/OCISessionManager"
license.file = "LICENSE"
author = "JCPhlux"
author_email = "jc@phluxapps.com"
icon = "resources/icon"

[tool.briefcase.app.ocisessionmanager]
formal_name = "OCI Session Manager"
description = "A tool for managing OCI Bastion sessions."
sources = ["src/ocisessionmanager"]
resources = ["ocisessionmanager/resources"]
requires = [
    "sv-ttk",
    "pillow",
    "oci",
    "cryptography",
    "pydantic",
    "pydantic-extra-types",
    "platformdirs",
]

[tool.briefcase.app.ocisessionmanager.mac]
universal_build = true
install_requires = [
    "tkinter",  # tkinter is included with Python on macOS, but needs to be specified for the build process
]
python = "https://www.python.org/ftp/python/3.13.2/python-3.13.2-macos11.pkg"
requires = [
    "darkdetect",
]

[tool.briefcase.app.ocisessionmanager.windows]
install_requires = ["tkinter"]
python = "https://www.python.org/ftp/python/3.13.2/python-3.13.2-amd64.exe"
requires = [
    "darkdetect",
    "pystray",
    "pywinstyles",
]

[tool.briefcase.app.ocisessionmanager.linux]
requires = [
    "pystray",
]
