name: Build and Release Tkinter App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
jobs:
  pyinstaller-build:
    runs-on: <windows-latest, ubuntu-latest, macos-latest>
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: "3.13"
          spec: "main.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "OCISessionManager"
          options: --onefile --noconsole --strip --clean --name OCISessionManager --add-data "resources;resources" --icon "resources/green_icon.ico"