name: Build and Release Tkinter App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of workflow
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: "5.0.0"
          install-only: true
      - name: Versatile PyInstaller (Windows)
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: "3.13.2"
          spec: "OCISessionManager.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "OCISessionManager-Windows"
          options: --onefile --noconsole --strip --clean --upx-dir uxp --add-data "resources;resources" --icon "resources/green_icon.ico"
  pyinstaller-build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: "5.0.0"
          install-only: true
      - name: Versatile PyInstaller (Ubuntu)
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: "3.13.2"
          spec: "OCISessionManager.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "OCISessionManager-Ubuntu"
          options: --onefile --noconsole --strip --clean --upx-dir upx --add-data "resources:resources" --icon "resources/green_icon.ico"
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Versatile PyInstaller (macOS)
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: "3.13.2"
          spec: "OCISessionManager.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "OCISessionManager-macOS"
          options: --onefile --noconsole --strip --clean --add-data "resources:resources" --icon "resources/green_icon.ico"
  create-release:
    needs:
      - pyinstaller-build-windows
      - pyinstaller-build-ubuntu
      - pyinstaller-build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Release Version
        id: version
        run: |
          TAG="v$(date +'%Y.%m.%d.%H%M')"
          echo "RELEASE_TAG=$TAG" >> "$GITHUB_ENV"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}

      - name: Generate changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=format:"%h - %s (%an)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: OCISessionManager-Windows
          path: dist/OCISessionManager-Windows

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: OCISessionManager-Ubuntu
          path: dist/OCISessionManager-Ubuntu

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: OCISessionManager-macOS
          path: dist/OCISessionManager-macOS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          body: |
            Changes:
            ${{ env.CHANGELOG }}
          files: dist/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
